{
 "title": "MSI Afterburner",
 "description": "Shows stats from MSI Afterburner",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "graphite", "label": "Graphite", "query": "graphite" },
   {
    "name": "afterburner",
    "label": "CollectD Metric Prefix",
    "query": "collectd.*.curl-xml-afterburner"
   }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "alias($afterburner.gauge-CPU_usage, 'CPU')"
    },
    {
     "target": "alias($afterburner.gauge-GPU_usage, 'GPU')"
    }
   ]
  },
  {
   "title": "GPU Limiting Factor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "targets": [
    {
     "target": "alias($afterburner.gauge-No_load_limit, 'No Load')"
    },
    {
     "target": "alias($afterburner.gauge-Power_limit, 'Power')"
    },
    {
     "target": "alias($afterburner.gauge-Temp_limit, 'Temperature')"
    },
    {
     "target": "alias($afterburner.gauge-Voltage_limit, 'Voltage')"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "target": "alias($afterburner.gauge-Framerate, 'FPS')"
    }
   ]
  },
  {
   "title": "FPS / Frametime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias($afterburner.gauge-Framerate, 'FPS')"
    },
    {
     "target": "alias($afterburner.gauge-Frametime, 'Frametime')"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "targets": [
    {
     "target": "alias($afterburner.gauge-CPU_temperature, 'CPU')"
    },
    {
     "target": "alias($afterburner.gauge-GPU_temperature, 'GPU')"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "targets": [
    {
     "target": "alias($afterburner.gauge-Frametime, 'FPS')"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias($afterburner.gauge-CPU_usage, 'CPU')"
    },
    {
     "target": "alias($afterburner.gauge-GPU_usage, 'GPU')"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "alias($afterburner.gauge-CPU_temperature, 'CPU')"
    },
    {
     "target": "alias($afterburner.gauge-GPU_temperature, 'GPU')"
    }
   ]
  },
  {
   "title": "Clockspeeds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "alias(scale($afterburner.gauge-CPU_clock, 1000000), 'CPU')"
    },
    {
     "target": "alias(scale($afterburner.gauge-Core_clock, 1000000), 'GPU')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "target": "alias($afterburner.gauge-RAM_usage, 'RAM')"
    },
    {
     "target": "alias($afterburner.gauge-Memory_usage, 'VRAM')"
    }
   ]
  },
  {
   "title": "Voltage / Memory Clock",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "alias(scale($afterburner.gauge-Memory_clock, 1000000), 'GPU Memory Clock')"
    },
    {
     "target": "alias($afterburner.gauge-GPU_voltage, 'Voltage')"
    }
   ]
  },
  {
   "title": "GPU Fans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias($afterburner.gauge-Fan_speed, 'Fan 1 Speed')"
    },
    {
     "target": "alias($afterburner.gauge-Fan_speed_2, 'Fan 2 Speed')"
    },
    {
     "target": "alias($afterburner.gauge-Fan_tachometer, 'Fan 1 rpm')"
    },
    {
     "target": "alias($afterburner.gauge-Fan_tachometer_2, 'Fan 2 rpm')"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "target": "alias($afterburner.gauge-CPU_power, 'CPU')"
    },
    {
     "target": "alias($afterburner.gauge-Power, 'GPU')"
    }
   ]
  }
 ]
}